imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    api.max_results_default: 20
    app.path.team_images: /uploads/images/teams

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_slugable:
                type: annotation
                prefix: Gedmo\Slugable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sluggable"
                is_bundle: false

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# EasyAdminBundle Configuration
easy_admin:
    site_name: 'Prode de Amigos'
    formats:
        datetime: 'd/m/Y H:i'
    entities:
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            list:
                title: 'Users'
                fields: ['username', 'email', 'enabled', 'facebookId', 'lastLogin']
        Tournament:
            class: AppBundle\Entity\Tournament
            label: 'Tournaments'
        Team:
            class: AppBundle\Entity\Team
            label: 'Teams'
            list:
                title: 'Teams'
                fields:
                    - name
                    - alias
                    - { property: 'flagUri', type: 'image' }
                    - stadium
            form:
                fields:
                    - name
                    - alias
                    - { property: 'flagFile', type: 'vich_image' }
                    - stadium
        Game:
            class: AppBundle\Entity\Game
            label: 'Games'
            list:
                fields: [ tournament, versus, playDateAt, result, finished ]
            form:
                fields:
                    - { property: 'tournament', type_options: { required: true, placeholder: 'None' } }
                    - { property: 'teamHome', type_options: { required: true, placeholder: 'None' } }
                    - { property: 'teamAway', type_options: { required: true, placeholder: 'None' } }
                    - playDateAt
                    - goalsHome
                    - goalsAway
                    - finished
        FantasyTournament:
            class: AppBundle\Entity\FantasyTournament
            label: 'Fantasy Tournaments'
            list:
                title: '%%entity_label%%'
            form:
                fields:
                    - name
                    - pointsPerGame
                    - matchExact
                    - { property: 'pointsPerExact', type_options: { required: false } }
                    - { property: 'tournament', type_options: { required: true, placeholder: 'None' } }
                    - { property: 'owner', type_options: { required: true, placeholder: 'None' } }
                    - members
            new:
                title: 'Create %%entity_label%%'
            edit:
                title: 'Edit %%entity_label%%'


# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Origin','Accept','Content-Type', 'Location']
        max_age: 3600
        hosts: []
        origin_regex: false

# FOSRest Configuration
fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api/*', priorities: ['json'], fallback_format: json, prefer_extension: false }
    zone:
        - { path: ^/api/* }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

# JMSSerializer Configuration
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            AppBundle:
                path: "@AppBundle/Resources/config/serializer"
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/Resources/FOSUserBundle/serializer"

# Vich Uploader
vich_uploader:
    db_driver: orm
    storage:   "@app.cloudinary_storage"
    mappings:
        team_images:
            uri_prefix:         '%app.path.team_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/teams'
            namer:              vich_uploader.namer_uniqid
