api_bundle:
  resource: "@AppBundle/Controller/"
  type:     annotation
  prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
