# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
    app.cloudinary_storage:
        class:     AppBundle\Storage\CloudinaryStorage
        arguments: ['@vich_uploader.property_mapping_factory']
    app.link_unlink_request_listener:
        class: AppBundle\EventListener\LinkUnlinkRequestListener
        arguments: ['@event_dispatcher', '@controller_resolver', '@router']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
