<?php

namespace AppBundle\Repository;

/**
 * FantasyTournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FantasyTournamentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * findByMembership() method
     * @param array $params
     * @param array $sortBy
     * @param integer $limit
     */
    public function findByMembership($params, $sortBy, $limit)
    {
        $query = $this->createQueryBuilder('ft')
            ->innerJoin('ft.members', 'ftm')
            ->where('ftm.id = :member_id');

        if (isset($params['slug'])) {
            $query->andWhere('ft.slug = :slug')
                ->setParameter('slug', $params['slug']);
        }

        $query->setParameter('member_id', $params['member_id']);
        $query = $query->getQuery();

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
