<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * findBetweenDates() method
     * @param AppBundle\Entity\Tournament
     * @param string $from (date string)
     * @param string $to (date string)
     */
    public function findBetweenDates($tournament, $from, $to)
    {
        $query = $this->createQueryBuilder('g')
            ->where('g.tournament = :tournament')
            ->andWhere('g.playDateAt >= :from')
            ->andWhere('g.playDateAt <= :to')
            ->orderBy('g.playDateAt', 'ASC');

        $query->setParameters(array(
            'tournament' => $tournament,
            'from' => $from,
            'to' => $to
        ));
        $query = $query->getQuery();

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
