---
- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/{{ php_version }}/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ php_timezone }}'