AppBundle\Entity\FantasyTournament:
    exclusion_policy: all
    properties:
        id:
            expose: true
        name:
            expose: true
        owner:
            expose: true
        pointsPerGame:
            expose: true
        matchExact:
            expose: true
        pointsPerExact:
            expose: true
        slug:
            expose: true
        memberships:
            expose: true
    virtual_properties:
        getPictureUri:
            serialized_name: picture_uri
            type: string
        getInvitationHash:
            serialized_name: invitationHash
            type: string