---
php_ppa: "ppa:ondrej/php"
php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-intl
  - php7.0-curl
  - php7.0-cgi
  - php7.0-fpm
  - php7.0-mysql
  - php7.0-gd
  - php7.0-mcrypt
php_timezone: America/Argentina/Cordoba
php_upload_max_filesize: "5M"
php_post_max_size: "5M"
php_memory_limit: "1024M"
php_max_execution_time: 60