---
php_ppa: "ppa:ondrej/php"
php_version: "7.1"
php_packages:
  - php{{ php_version }}-common
  - php{{ php_version }}-cli
  - php{{ php_version }}-intl
  - php{{ php_version }}-curl
  - php{{ php_version }}-cgi
  - php{{ php_version }}-fpm
  - php{{ php_version }}-mysql
  - php{{ php_version }}-gd
  - php{{ php_version }}-mcrypt
  - php{{ php_version }}-xml
php_timezone: America/Argentina/Cordoba
php_upload_max_filesize: "5M"
php_post_max_size: "5M"
php_memory_limit: "1024M"
php_max_execution_time: 60
php_opcache_max_accelerated_files: 20000